### ISSUE TITLE
 [ExceptionHandler] metatype is not a constructor

### ISSUE THREAD

**Issue by adhranjan** [nest-cloud/nestcloud-grpc-example#1]
when i import 
          ConsulServiceModule.register({dependencies: [NEST_BOOT],}),
         LoadbalanceModule.register({ dependencies: [NEST_BOOT], }),

inside the app module

TypeError: metatype is not a constructor
    at Injector.instantiateClass (/home/user/bigtix-nest-cart/node_modules/@nestjs/core/injector/injector.js:284:19)
    at callback (/home/user/bigtix-nest-cart/node_modules/@nestjs/core/injector/injector.js:75:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by miaowing** [comment]
I have updated this repository，please retry again, if the problem still occur contact me, thank you~

**Comment by adhranjan** [comment]
perfect, thank you
